### PR TITLE
[ver] 0.2.4

### PR DESCRIPTION
**Pull request by nosovk**
publish new version with https://github.com/codefeathers/rollup-plugin-svelte-svg/issues/18 fix included

### CODE REVIEW

**Comment by MTyson** [comment]
Need this please.

**Comment by MKRhere** [comment]
Sorry for the delay. I have a few more fixes locally, will publish later today after work.

**Comment by MTyson** [comment]
Right on, appreciate your work.

**Comment by romdim** [comment]
Hello there, would really appreciate it if you could push :)
Thanks!

**Comment by MKRhere** [comment]
Well, it's been a rough few months (years?).
Published a new version `1.0.0-beta1`. While updating, remember to make this change in your config:

```diff
-import svelteSVG from "rollup-plugin-svelte-svg";
+import { svelteSVG } from "rollup-plugin-svelte-svg";
```

**Pull request closed without merging**
